2025-10-03T19:12:35 {"cpu": 1.6396484375, "cpu_total": 8, "cpu_usage": 0.2049560546875, "memory": 4491.0, "memory_total": 8924.0, "memory_usage": 0.5032496638278798, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518755.21454, "uuid": "449f7a306ebb455ba7b159eb896f90f2"}
2025-10-03T19:12:38 {"cpu": 1.6416015625, "cpu_total": 8, "cpu_usage": 0.2052001953125, "memory": 4491.0, "memory_total": 8924.0, "memory_usage": 0.5032496638278798, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518758.04451, "uuid": "f350a9f6171242db92c1812db6ac30f6"}
2025-10-03T19:12:42 {"cpu": 1.6416015625, "cpu_total": 8, "cpu_usage": 0.2052001953125, "memory": 4491.0, "memory_total": 8924.0, "memory_usage": 0.5032496638278798, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518762.213375, "uuid": "2fbea76442bf45c9ace1a5c40071c5e7"}
2025-10-03T19:12:52 {"cpu": 1.64501953125, "cpu_total": 8, "cpu_usage": 0.20562744140625, "memory": 4479.0, "memory_total": 8924.0, "memory_usage": 0.5019049753473779, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518772.253675, "uuid": "796402d95d3c48f9880ffebc10e6dd96"}
2025-10-03T19:13:02 {"cpu": 1.63720703125, "cpu_total": 8, "cpu_usage": 0.20465087890625, "memory": 4667.0, "memory_total": 8924.0, "memory_usage": 0.5229717615419095, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518782.162602, "uuid": "73417fc59b6e4be3b99f369bc837837e"}
2025-10-03T19:13:09 {"block_run_id": 24, "block_uuid": "ingest_data", "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Execute PipelineRun 25, BlockRun 24: pipeline backfill_taxis_zones block ingest_data", "timestamp": 1759518788.979416, "uuid": "f2c76aa6b05944ffb99a50c395a2e182"}
2025-10-03T19:13:12 {"cpu": 1.63525390625, "cpu_total": 8, "cpu_usage": 0.20440673828125, "memory": 4509.0, "memory_total": 8924.0, "memory_usage": 0.5052666965486329, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518792.245534, "uuid": "97fb00580b724b39a6d51f8642e2f9b4"}
2025-10-03T19:13:22 {"cpu": 1.62841796875, "cpu_total": 8, "cpu_usage": 0.20355224609375, "memory": 4520.0, "memory_total": 8924.0, "memory_usage": 0.5064993276557598, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518802.233914, "uuid": "df0cdd1cda9e49d2bffb172ed1273330"}
2025-10-03T19:13:32 {"cpu": 1.62158203125, "cpu_total": 8, "cpu_usage": 0.20269775390625, "memory": 4528.0, "memory_total": 8924.0, "memory_usage": 0.5073957866427611, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518812.472473, "uuid": "67a558a84fe64ca3a1623e37d1094d4d"}
2025-10-03T19:13:42 {"cpu": 1.61474609375, "cpu_total": 8, "cpu_usage": 0.20184326171875, "memory": 4369.0, "memory_total": 8924.0, "memory_usage": 0.48957866427610935, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518822.742198, "uuid": "23acb82840cd400a8eb8e6d17dc6f2b9"}
2025-10-03T19:13:52 {"cpu": 1.619140625, "cpu_total": 8, "cpu_usage": 0.202392578125, "memory": 4687.0, "memory_total": 8924.0, "memory_usage": 0.5252129090094129, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518832.442979, "uuid": "d7ea046cd236443a9f0dd068c8bd2235"}
2025-10-03T19:14:02 {"cpu": 1.6240234375, "cpu_total": 8, "cpu_usage": 0.2030029296875, "memory": 4538.0, "memory_total": 8924.0, "memory_usage": 0.5085163603765128, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518842.458419, "uuid": "72789b4b11bc400b84f373e97ad872e0"}
2025-10-03T19:14:03 {"block_run_id": 24, "block_uuid": "ingest_data", "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "EXCEPTION", "message": "BlockRun 24 (block_uuid: ingest_data) failed.", "timestamp": 1759518843.110303, "uuid": "96af7d4a56114e579986d8d09aa58973", "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1691, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1668, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1570, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1910, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2073, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2169, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 34, in load_data\nTypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'\n", "error_stack": ["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1442, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1830, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1226, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 794, in invoke\n    return callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 809, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 108, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 60, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1702, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 197, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 333, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 640, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 122, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 199, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 353, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 317, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1235, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 159, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 464, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack()\n"], "error_stacktrace": "int() argument must be a string, a bytes-like object or a real number, not 'NoneType'"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1691, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1668, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1570, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1910, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2073, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2169, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 34, in load_data
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2025-10-03T19:14:11 {"cpu": 1.61181640625, "cpu_total": 8, "cpu_usage": 0.20147705078125, "memory": 4494.0, "memory_total": 8924.0, "memory_usage": 0.5035858359480054, "pipeline_run_id": 25, "pipeline_schedule_id": 4, "pipeline_uuid": "backfill_taxis_zones", "hostname": "7915031173d5", "level": "INFO", "message": "Pipeline backfill_taxis_zones for run 25 in schedule 4 is alive.", "timestamp": 1759518851.914325, "uuid": "d327fec14a184085a12c60714ec4869d"}
